version: '3'

services:
  mirror:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./links.yaml:/app/links.yaml
      - ./config.ini:/app/config.ini
      - ./files:/app/files
      - ./logs:/app/logs